version: "3.7"
services:
    app:
        build:
            args:
                user: laravel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: always
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        networks:
            - app-network

    # nginx
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - app-network

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
